name: laravel-2

services:
  # El "motor" de PHP
  app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: laravel-2-app
    volumes:
      - ..:/var/www
    networks:
      - web

  # El servidor Web (Nginx) que conecta con Traefik
  webserver:
    image: nginx:alpine
    container_name: laravel-2-web
    volumes:
      - ..:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web
    labels:
      - "traefik.enable=true"
      # Usamos la variable para el dominio
      - "traefik.http.routers.laravel-2.rule=Host(`laravel-2.localhost`)"
      - "traefik.http.routers.laravel-2.entrypoints=web"
      - "traefik.http.services.laravel-2.loadbalancer.server.port=80"
      - "traefik.docker.network=web"

networks:
  web:
    external: true
